In [1]:
import numpy as np

def exponentially_decaying_array(n, decay_factor):
    return decay_factor ** np.arange(n)

start_value = 0.1
n = 4
decay_factor = 0.1  # This is the factor by which each subsequent element decays

decay_array = exponentially_decaying_array(n, decay_factor)
print(decay_array)


[1.    0.1   0.01  0.001]


In [2]:
import numpy as np

# Creating the first array of size 10
first_array = np.arange(10)
print(first_array)

# Creating the second array of size 4
second_array = np.array([1, 2, 3, 4])
print(second_array)

# Adding the second array to the first array at index 3 to 6
first_array[3:7] += second_array

print(first_array)


[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4]
[ 0  1  2  4  6  8 10  7  8  9]


In [6]:
a = np.arange(4)
print(a)
b = a * 5
print(b)

[0 1 2 3]
[ 0  5 10 15]
